name: Staging Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    tags:        
      - 'v*.*.*'
jobs:
  Deploy-Staging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }} # This could be changed to staging in Pro plan

      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      # Deploy to Vercel Preview (can be changed to staging)
      - name: Deploy Project Artifacts to Vercel
        id: deploy
        run: |
          # Deploy with Vercel CLI as Preview
          url=$(vercel --token $VERCEL_TOKEN --prebuilt --confirm --prod=false --yes)
          echo "preview_url=$url" >> $GITHUB_OUTPUT

      - name: Alias deployment
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          npx vercel alias set ${{ steps.deploy.outputs.preview_url }} staging-portfolio-charlie-eight.vercel.app --token $VERCEL_TOKEN