name: Deploy Staging

on:
  push:
    tags:
      - "staging-*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Node.js
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      # Install Vercel CLI
      - name: Install Vercel CLI
        run: npm install -g vercel

      # Deploy to Vercel Preview
      - name: Deploy to Staging
        id: deploy
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}   # <-- Make token available
        run: |
          # Deploy with Vercel CLI as Preview
          url=$(vercel --token $VERCEL_TOKEN --confirm --prod=false --yes)
          echo "preview_url=$url" >> $GITHUB_OUTPUT

      # Alias deployment to staging.myapp.vercel.app
      - name: Alias deployment
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          npx vercel alias set ${{ steps.deploy.outputs.preview_url }} staging-portfolio-charlie-virid.vercel.app --token $VERCEL_TOKEN
